Examples and readme
geoelements/gns-inverse-examples pull request #1
Opened 2024-01-23 16:34 UTC by yjchoi1

added examples and readme

2024-01-23 21:52 UTC, kks32 requested changes
Please don't include the whole GNS code here. It should be using the exisitng GNS. If you want to tie to a specific version of GNS code, then use gitsubmodule for that commit.

2024-01-24 00:02 UTC, yjchoi1 commented
Added the submodule with the specific commit.

2024-01-24 00:05 UTC, kks32 requested changes
Add this command on how to checkout `git submodule update --init --recursive`

Don't you need to checkout a specific commit of GNS? I thought it only wokred with a specifiv version of GNS?

2024-01-24 00:10 UTC, kks32 requested changes

2024-01-24 00:10 UTC, kks32 commented on inverse_barrier/inverse.py
> +
```suggestion
```

Remove these

2024-01-24 00:10 UTC, kks32 commented on inverse_barrier/optimizations.py
> +#     return loss
If not used remove these?

2024-01-24 00:10 UTC, kks32 commented on inverse_velocity/loss_landscape.py
> +sys.path.append("/work2/08264/baagee/frontera/gns-main/")
Don't use hardcoded paths especially on public repos. Others should be able to reproduce.

2024-01-24 00:10 UTC, kks32 commented on inverse_velocity/loss_landscape.py
> +path = "data/"
If you are expecting it in `data/` either make sure the script does this or specify in the README

2024-01-25 04:47 UTC, yjchoi1 commented
I have included the requests.

2024-01-25 06:47 UTC, merged